### ISSUE TITLE
Build and run outside Docker

### ISSUE THREAD

**Issue by drequivalent** [yukimochi/Activity-Relay#25]
How do I build and run the relay in a production environment, without Docker?

**Comment by yukimochi** [comment]
Thank you for creating an issue.

If you want running this relay outside Docker, need 2-steps, "build" and "run".

## build

**need Go envrionment (Use latest is recommend.)**

```bash
$ git clone https://github.com/yukimochi/Activity-Relay.git -b v0.2.4
$ cd Activity-Relay
$ go build .
$ go build ./cli
$ go build ./worker
```

you can got 3-binaries, "Activity-Relay", "worker", "cli".
Only you need have to running relay service is them and `config.yml.example`.

## run

**Prepare Redis server separately.**
**Rename and edit `config.yml.example` -> `config.yml`**

1. run server

```bash
$ ./Activity-Relay
```

1. run worker

```bash
$ ./worker
```

**`config.yml` should be in Working Directory**

You want auto-run and auto-restart when system starts, setup sysvinit, systemd, openrc and so on...

## Remarks

I don't recommend runnging outside Docker to earn support others.
When you encount problems, be hard to reproduction it, because many environment is exist in the world.

*Note: `YUKIMOCHI Toot Relay Service` is running on kubernates using my DockerHub images.*

**Comment by drequivalent** [comment]
Thanks!
