### ISSUE TITLE
Dockerによる起動に失敗する

### ISSUE THREAD

**Issue by MitarashiDango** [yukimochi/Activity-Relay#42]
## 事象
Dockerによる初回起動時に以下エラーを出力し、起動に失敗します。

```
go: github.com/RichardKnop/machinery@v1.7.8: missing go.sum entry; to add it:
	go mod download github.com/RichardKnop/machinery
ERROR: Service 'worker' failed to build: The command '/bin/sh -c mkdir -p /rootfs/usr/bin &&      apk add -U --no-cache git &&      go build -o /rootfs/usr/bin/server -ldflags "-X main.version=$(git describe --tags HEAD)" . &&      go build -o /rootfs/usr/bin/worker -ldflags "-X main.version=$(git describe --tags HEAD)"  ./worker &&      go build -o /rootfs/usr/bin/ar-cli -ldflags "-X main.version=$(git describe --tags HEAD)"  ./cli' returned a non-zero code: 1
```

## 推測される原因
Go 1.16以降ではgo.modまたはgo.sumの自動修正が行われないため、依存モジュールの解決に失敗しているものと推測されます。

参考:
https://blog.golang.org/go116-module-changes
※「No automatic changes to go.mod and go.sum」を参照ください。

**Comment by yukimochi** [comment]
docker pull じゃなくて、 build された感じですよね。
ライブラリバージョン上げて、バージョン切ろうかな…。

**Comment by shyamean4151** [comment]
私もこのミスに遭いました。どう解決すればいいですか？

**Comment by yukimochi** [comment]
さしあたり、 Go 1.13 を指定するように Dockerfile 一行目を `FROM golang:1.13-alpine AS build` と置換していただけるとビルドが可能です。
Go 1.13 が最終確認バージョンとなります。 Go 1.16 の動作確認等については、時間をいただいています。

**Comment by shyamean4151** [comment]
Successfully built 112ae6d82aa2
Successfully tagged yukimochi/activity-relay:latest
WARNING: Image for service worker was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating activityrelay_redis_1 ... 
Creating activityrelay_redis_1 ... done                                                Creating activityrelay_worker_1 ... 
Creating activityrelay_server_1 ... 
Creating activityrelay_worker_1
Creating activityrelay_server_1 ... done                                               root@HostKvm-332330:~/Activity-Relay# docker-compose build                             redis uses an image, skipping
Building worker
Step 1/7 : FROM golang:1.13-alpine AS build
 ---> 5863598a981a
Step 2/7 : WORKDIR /Activity-Relay
 ---> Using cache
 ---> 62161efdb996
Step 3/7 : COPY . /Activity-Relay
 ---> Using cache
 ---> 45abdd4548fb
Step 4/7 : RUN  mkdir -p /rootfs/usr/bin &&      apk add -U --no-cache git &&      go build -o /rootfs/usr/bin/server -ldflags "-X main.version=$(git describe --tags HEAD)" . &&      go build -o /rootfs/usr/bin/worker -ldflags "-X main.version=$(git describe --tags HEAD)"  ./worker &&      go build -o /rootfs/usr/bin/ar-cli -ldflags "-X main.version=$(git describe --tags HEAD)"  ./cli
 ---> Using cache
 ---> 3426b98469b8
                                                                                       Step 5/7 : FROM alpine
 ---> 302aba9ce190
Step 6/7 : COPY --from=build /rootfs/usr/bin /usr/bin
 ---> Using cache
 ---> 13d29bf76586
Step 7/7 : RUN  chmod +x /usr/bin/server /usr/bin/worker /usr/bin/ar-cli &&      apk add -U --no-cache ca-certificates
 ---> Using cache
 ---> 112ae6d82aa2
                                                                                       Successfully built 112ae6d82aa2
Successfully tagged yukimochi/activity-relay:latest
Building server
Step 1/7 : FROM golang:1.13-alpine AS build
 ---> 5863598a981a
Step 2/7 : WORKDIR /Activity-Relay
 ---> Using cache
 ---> 62161efdb996
Step 3/7 : COPY . /Activity-Relay
 ---> Using cache
 ---> 45abdd4548fb
Step 4/7 : RUN  mkdir -p /rootfs/usr/bin &&      apk add -U --no-cache git &&      go build -o /rootfs/usr/bin/server -ldflags "-X main.version=$(git describe --tags HEAD)" . &&      go build -o /rootfs/usr/bin/worker -ldflags "-X main.version=$(git describe --tags HEAD)"  ./worker &&      go build -o /rootfs/usr/bin/ar-cli -ldflags "-X main.version=$(git describe --tags HEAD)"  ./cli
 ---> Using cache
 ---> 3426b98469b8
                                                                                       Step 5/7 : FROM alpine
 ---> 302aba9ce190
Step 6/7 : COPY --from=build /rootfs/usr/bin /usr/bin
 ---> Using cache
 ---> 13d29bf76586
Step 7/7 : RUN  chmod +x /usr/bin/server /usr/bin/worker /usr/bin/ar-cli &&      apk add -U --no-cache ca-certificates
 ---> Using cache
 ---> 112ae6d82aa2
                                                                                       Successfully built 112ae6d82aa2
Successfully tagged yukimochi/activity-relay:latest
正常に動作していません

**Comment by shyamean4151** [comment]
えっと、すみません、RSAで問題が発生しました。解決しました。

**Comment by shyamean4151** [comment]
ログ出力は正常ですが、今はヒント502のエラーを開けられません。
https://relay.neko.ci/

**Comment by shyamean4151** [comment]
LOG:
Config file is not exists. Use environment variables.
Welcome to YUKIMOCHI Activity-Relay [Server] v0.2.8
 - Configurations
RELAY DOMAIN :  relay.neko.ci
REDIS URL :  redis://redis:6379
BIND ADDRESS :  127.0.0.1:8051
 - Blocked Domain
 - Limited Domain
 
Welcome to YUKIMOCHI Activity-Relay [Worker] v0.2.8
 - Configurations
RELAY DOMAIN :  relay.neko.ci
REDIS URL :  redis://redis:6379
[0;94mINFO: 2021/03/29 16:19:54 worker.go:56 Launching a worker with the following settings:
[0;94mINFO: 2021/03/29 16:19:54 worker.go:57 - Broker: redis://redis:6379
[0;94mINFO: 2021/03/29 16:19:54 worker.go:59 - DefaultQueue: relay
[0;94mINFO: 2021/03/29 16:19:54 worker.go:63 - ResultBackend: redis://redis:6379
[0;94mINFO: 2021/03/29 16:19:59 redis.go:94 [*] Waiting for messages. To exit press CTRL+C

1:C 29 Mar 2021 16:19:56.113 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 29 Mar 2021 16:19:56.113 # Redis version=6.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 29 Mar 2021 16:19:56.113 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
1:M 29 Mar 2021 16:19:56.114 * monotonic clock: POSIX clock_gettime
1:M 29 Mar 2021 16:19:56.115 * Running mode=standalone, port=6379.
1:M 29 Mar 2021 16:19:56.115 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 29 Mar 2021 16:19:56.115 # Server initialized
1:M 29 Mar 2021 16:19:56.116 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 29 Mar 2021 16:19:56.116 * Loading RDB produced by version 6.2.1
1:M 29 Mar 2021 16:19:56.116 * RDB age 8 seconds
1:M 29 Mar 2021 16:19:56.116 * RDB memory usage when created 0.77 Mb
1:M 29 Mar 2021 16:19:56.116 * DB loaded from disk: 0.000 seconds
1:M 29 Mar 2021 16:19:56.116 * Ready to accept connections

**Comment by yukimochi** [comment]
この issue とは関係ない問題と思いますので、別途問題があれば報告ください。

502 エラーについては、あなたのリバースプロキシの仕様に大きく影響しますので、原因の特定は困難です。
なお、 Docker において Bind アドレスに `127.0.0.1` は Docker のネットワーク構造について詳しく理解していないなら推奨しません。 `0.0.0.0` で Bind されることを推奨します。

**Comment by yukimochi** [comment]
`v0.2.9` において、 Go 1.16 をサポートしました。
